[package]
name = "skidmarks"
version = "0.1.0"
edition = "2021"

[dependencies]
ansi_term = "0.12.1"
assert_cmd = "2.0.15"
assert_fs = "1.1.2"
catppuccin = { version = "2.4.0", features = ["ansi-term"] }
chrono = { version = "0.4.38", features = ["serde"] }
clap = { version = "4.5.11", features = ["derive"] }
config = "0.14.0"
console = "0.15.8"
lazy_static = "1.5.0"
ron = "0.8.1"
serde = { version = "1.0.204", features = ["derive"] }
