[package]
name = "skidmarks"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.38", features = ["serde"] }
clap = { version = "4.5.11", features = ["derive"] }
ron = "0.8.1"
serde = { version = "1.0.204", features = ["derive"] }
