[application]
name = "Skidmarks"
default_platform = "desktop"
out_dir = "dist"
asset_dir = "assets"

[web.app]
title = "Skidmarks"

[web.watcher]
reload_html = true
watch_path = ["src", "assets"]

[web.resources]
style = ["streaks.css"]
script = []

[web.resources.dev]
script = []