[package]
name = "skidmarks"
version = "0.1.9"
edition = "2021"
description = "A CLI for tracking streaks"
repository = "https://github.com/kennethlove/skidmarks"
readme = "README.md"
license = "Apache-2.0"
keywords = ["cli", "streaks", "habits"]
categories = ["command-line-utilities"]

[dependencies]
ansi_term = "0.12.1"
clap = { version = "4.5.11", features = ["derive"] }
console = "0.15.8"
dirs = "5.0.1"
uuid = { version = "1.10.0", features = ["serde", "v4", "fast-rng"] }
assert_cmd = "2.0.15"
assert_fs = "1.1.2"
term_size = "0.3.2"
tabled = "0.17.0"

shared = { path = "../shared" }
streak = { path = "../streak" }
textwrap = "0.16.1"

[dev-dependencies]
rstest = "0.23.0"

[[bin]]
name = "skidmarks-cli"
path = "src/main.rs"

